version: '3.10'
services:
    database:
        container_name: DTAPI
        image: postgres:13.1-alpine
        environment:
            POSTGRES_DB: datab
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            PGDATA: /var/lib/postgresql/data
        ports:
            - 5432:5432
        volumes:
            - ./db:/var/lib/postgresql/data
        restart: always

